# Generated by Django 5.1.4 on 2024-12-19 19:24

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                validators=[accounts.models.validate_profile_picture],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("ONLINE", "Online"), ("OFFLINE", "Offline")],
                default="OFFLINE",
                max_length=10,
            ),
        ),
    ]
