# Generated by Django 5.1.4 on 2025-01-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customuser_first_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="first_login",
            new_name="is_first_login",
        ),
    ]
