# Generated by Django 5.1.4 on 2024-12-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='status_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
