# Generated by Django 5.1.4 on 2024-12-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_is_favorite_contact_status_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="status_text",
        ),
    ]
