# Generated by Django 5.1.4 on 2025-01-03 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_owner'),
        ('messaging', '0002_message_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_read_message_chat', to='messaging.message'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('owner', 'user')},
        ),
    ]
