# Generated by Django 5.1.4 on 2025-01-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_groupchatmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupchatmessage",
            options={"get_latest_by": "created_at", "ordering": ["created_at"]},
        ),
    ]
