# Generated by Django 5.1.4 on 2025-01-14 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_messagereadstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageReadStatus',
            new_name='GroupChatMessageReadStatus',
        ),
        migrations.AlterField(
            model_name='groupchatmessagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.groupchatmessage'),
        ),
    ]
