# Generated by Django 5.1.4 on 2025-01-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "messaging",
            "0008_rename_messagereadstatus_groupchatmessagereadstatus_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupchatmessagereadstatus",
            options={"get_latest_by": "read_at"},
        ),
    ]
